import path from "node:path";
import { fileURLToPath } from "node:url";

const config = {
    dataDir: path.resolve(path.dirname(fileURLToPath(import.meta.url)), "data"),
    terms: [
        { name: "2026 Fall", active: true, finalized: false },
        { name: "2026 Summer", active: true, finalized: false },
        { name: "2026 Spring", active: false, finalized: true },
        { name: "2025 Fall", active: false, finalized: true },
    ],
    schools: {
        "Arts & Sciences": [
            "African and African-American Studies",
            "American Culture Studies",
            "Anthropology",
            "Art History and Archaeology",
            "Biology",
            "Center for the Humanities",
            "Chemistry",
            "Classics",
            "College Office",
            "College Writing Program",
            "Comparative Literature and Thought",
            "Division of Biology and Biomedical Sciences",
            "Earth, Environmental, and Planetary Sciences",
            "East Asian Languages and Cultures",
            "Economics",
            "Education",
            "English",
            "Environmental Studies",
            "Film and Media Studies",
            "Global Studies",
            "History",
            "Interdisciplinary Project in The Humanities",
            "Jewish, Islamic, and Middle Eastern Studies",
            "Latin American Studies",
            "Linguistics",
            "Mathematics",
            "Music",
            "Performing Arts",
            "Philosophy",
            "Philosophy-Neuroscience-Psychology",
            "Physical Education",
            "Physics",
            "Political Science",
            "Psychological & Brain Sciences",
            "Public Health and Society",
            "Religious Studies",
            "Romance Languages and Literatures",
            "Sociology",
            "Statistics and Data Science",
            "Women, Gender, and Sexuality Studies",
        ],
        "Brown School": [],
        "McKelvey School of Engineering": [
            "Biomedical Engineering",
            "Computer Science & Engineering",
            "Division of Engineering Education",
            "Electrical & Systems Engineering",
            "Energy, Environmental & Chemical Engineering",
            "Mechanical Engineering & Materials Science",
            "Sever Institute",
            "UMSL/WashU Joint Undergraduate Engineering Program",
        ],
        "Olin Business School": [],
        "Sam Fox School of Design & Visual Arts": [
            "College of Art",
            "College of Architecture",
        ],
        "Washington University in St. Louis": [
            "Beyond Boundaries",
            "Inter-University Exchange",
            "Military Affairs",
        ],
    },
};

export default config;
